version: '3.7'

services:
  database:
    build: ./postgresql
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=095f75fe10f6541b51d4a1ca84a993ac274ac14bee50a6c7a7df6c79cffd1946
      - POSTGRES_DB=app
    restart: unless-stopped
  backend:
      build: ./backend
      # ports:
      #   - '8888:8888'
      depends_on:
        - database
      restart: unless-stopped
  frontend:
      build: ./frontend
      # ports:
      #   - '3000:80'
      # volumes:
      #   - ./frontend:/app
      depends_on:
        - backend
      environment:
        - GOOGLE_CLIENT_ID=180175983654-eb9bg6s9hm9ef3ieisij8f31t0hi5f0l.apps.googleusercontent.com
      restart: unless-stopped
  nginx:
      build: ./nginx
      ports:
        - '80:80'
        - '443:443'
      depends_on:
        - frontend
        - backend
        - database
      restart: unless-stopped
  hardhat:
      build: ./hardhat
      stdin_open: true
      tty: true
      ports: 
        - '8545:8545'
      restart: unless-stopped
  

